### ISSUE TITLE
Courses on beta - issues list for today

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#486]
Hey team,

Anything on this list is priority 1. Course start Wednesday morning.

Thanks.

- [ ] Some users can't create their profiles
- One user reports that they never received their verification code (possible user error).
- Another user reports that they got a blank screen after confirming their email, but he then removed extra fields from url and was able to get it (possible accidental refresh got him in)
- One user tried to login supposedly after creating account and received the error "user does not exist" (possible user error). 

- [x] "Respond" assignment requires admin to select the assignment that the user is responding to. Though the assignments drop down displays, admin cannot save the selection.

- [x] Text inputted into text boxes (i.e. second text box under Week 1) gets added behind and below the assignment boxes. Rather, the assignment boxes should shift down as text is entered.

- [x] When the admin clicks "edit course" and then selects text to edit, the text that was there disappears and the admin needs to re-enter all text rather than simply edit it.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem  For the users, I will need more information...I looked up the name you gave me and everything looks ok with her.

**Comment by GeorgeBellTMH** [comment]
Text inputted into text boxes (i.e. second text box under Week 1) gets added behind and below the assignment boxes. Rather, the assignment boxes should shift down as text is entered. @mmacedom can you check the autosizing of all the editabletextboxes and other dynamically sized objects in safari? I think it works ok on chrome...

**Comment by lucastbelem** [comment]
Hey George,

I was on Chrome and was seeing this issue...unless you mean it's an issue
related to safari for the admin who inputted the text.

**Comment by GeorgeBellTMH** [comment]
I think Mateus fixed it on chrome...

**Comment by GeorgeBellTMH** [comment]
(not published yet)

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem Yes, the issue has been fixed on Chrome both on edit and non edit modes. On edit mode, the second field is scrollable however, once saved, all of the copy content pushes the assignments down. See below. I will check on Safari

<img width="1136" alt="Screen Shot 2020-10-05 at 9 17 40 PM" src="https://user-images.githubusercontent.com/24467324/95148012-5c2a8280-0750-11eb-8bca-b7a88def6e93.png">
<img width="1070" alt="Screen Shot 2020-10-05 at 9 17 45 PM" src="https://user-images.githubusercontent.com/24467324/95148013-5cc31900-0750-11eb-8960-6a4b23ff681f.png">

**Comment by mmacedom** [comment]
@GeorgeBellTMH I took a look on Safari and the issue is replicable. What's the best way to assign webkit fallback in React?

**Comment by GeorgeBellTMH** [comment]
I've added react-device-detect ... you should be able to do:

import {
    isSafari,
    isChrome
} from "react-device-detect";


{isSafari?"#ffffff":"#000000}

**Comment by lucastbelem** [comment]
@mmacedom just confirming this needs implementing still? George published last night and I still see the issue, so just wanted to make sure.

Also, fyi, I'm on Chrome and I when I enter text, I still get the problem:
<img width="1189" alt="Screen Shot 2020-10-06 at 8 25 21 AM" src="https://user-images.githubusercontent.com/48295718/95201173-88282100-07ad-11eb-96ac-0cd31a12daf5.png">

**Comment by GeorgeBellTMH** [comment]
Can you clear your cache...that might fix it.

Sent from my iPhone

On Oct 6, 2020, at 8:26 AM, Lucas Belem <notifications@github.com> wrote:

﻿

@mmacedom<https://github.com/mmacedom> just confirming this needs implementing still? George published last night and I still see the issue, so just wanted to make sure.

Also, fyi, I'm on Chrome and I when I enter text, I still get the problem:
[Screen Shot 2020-10-06 at 8 25 21 AM]<https://user-images.githubusercontent.com/48295718/95201173-88282100-07ad-11eb-96ac-0cd31a12daf5.png>

**Comment by lucastbelem** [comment]
No luck.

**Comment by mmacedom** [comment]
@lucastbelem I still have to add the Safari fallbacks but Chrome should be working at this point.

**Comment by lucastbelem** [comment]
@mmacedom my screenshot is on chrome.

**Comment by lucastbelem** [comment]
Weird...it worked now...maybe the cache thing was taking a while.

**Comment by lucastbelem** [comment]
@mmacedom ok, here is the issue I got. It looks like when there are no lesson boxes, it works fine. But as soon as I add a box, the text goes behind it.

<img width="847" alt="Screen Shot 2020-10-06 at 10 42 12 AM" src="https://user-images.githubusercontent.com/48295718/95216939-a8151000-07c0-11eb-8da7-9eba46c4abea.png">

**Comment by lucastbelem** [comment]
Here is the screenshot of what it looks like without a lesson box.
<img width="710" alt="Screen Shot 2020-10-06 at 10 43 10 AM" src="https://user-images.githubusercontent.com/48295718/95217035-bfec9400-07c0-11eb-9710-377c0c33b507.png">

**Comment by mmacedom** [comment]
@lucastbelem Great. I'll try to replicate the issue on my end.

**Comment by mmacedom** [comment]
@lucastbelem I am still not able to replicate the issue on my local (I sent you a video to your phone, Github won't let me know add it here cause it's too big) and it will be tough to implement any sort of fix if I can't replicate it. @GeorgeBellTMH do you have any suggestions on this?

**Comment by GeorgeBellTMH** [comment]
I've fixed it and am pushing

**Comment by GeorgeBellTMH** [comment]
@mmacedom fyi, Lucas was getting a really old version of the codebase because expo changed their default settings to disable the service worker...

**Comment by mmacedom** [comment]
@GeorgeBellTMH Great news! Glad to hear the issue was found.
