### ISSUE TITLE
Buttons on resources not working and scrolling issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#918]
It happens on all pages of every resource. (This is just an example:  https://beta.jesuscollective.com/app/resource?groupType=null&id=resource-1630337326814&create=false)

1. Nothing happens when I click on Add Page Item. The other buttons at the bottom of the page are working. And a dialog box opens up when I click on the Gear icon.

![image (4)](https://user-images.githubusercontent.com/48295718/137372267-5816f412-171e-4e98-8383-12627de6d73b.png)

1. Everytime I go to a new resource, I'm not able to scroll through the page. It only works after I have refreshed the page.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=773361055)

**Comment by GeorgeBellTMH** [comment]
Can you verify the scrolling is fixed?

**Comment by GeorgeBellTMH** [comment]
I am no longer able to replicate the scrolling issue...

**Comment by lucastbelem** [comment]
Interesting...neither am I. I'll let the team know so they can all verify on their end too, but I think we can close for now.

What do you think may have solved it?

**Comment by GeorgeBellTMH** [comment]
No idea…..

**Comment by lucastbelem** [comment]
@GeorgeBellTMH issue is not resolved. 

Zulema still encounters it in Resources, but not Courses. She is using up to date Chrome, and up to date Windows.

**Comment by GeorgeBellTMH** [comment]
I need a way to replicate this...can somebody else other than Zulema confirm it is happening in windows?

**Comment by itbel** [comment]
Yep, it's still happening for me. 
Windows 10, latest chrome version.
Steps to replicate:
- Navigate to beta.jesuscollective.com
- Click resources dropdown, select one story curriculum
- Cant scroll. (Desktop view)
Having device toolbar toggled on in chrome dev tools seems to prevent the issue from happening

The issue disappears if you refresh the page.

**Comment by itbel** [comment]
Try incognito if the issue will not replicate, starting from the dashboard (not direct link to the resource).

**Comment by lucastbelem** [comment]
This issue is partially resolved, so I'm closing and creating a new one for the persisting bug.
